version: '2.2'
services:
  amiami:
    build: .    
    volumes:
      - ./data/projects:/projects
    networks:
      - backend

  mysql_amiami:
    image: mysql:8.0
    # image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    security_opt:
    - seccomp:unconfined
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
      # Where our data will be persisted
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - backend

# Names our volume
volumes:
  db_volume:
    external: true
  amiami_volume:
    external: true

networks:
  backend:
    external: true
